"Name: \PR:SAPMV50A\FO:USEREXIT_SAVE_DOCUMENT\SE:BEGIN\EI
ENHANCEMENT 0 Z1013492_MF.
*
  IF sy-uname = 'TEJAG'.
    IF lips-lgort IS INITIAL.
      MESSAGE 'FILL THE STORAGE LOCATION' TYPE 'I'.
    ENDIF.
  ENDIF.
ENDENHANCEMENT.
