*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: Z1013492_MAINT..................................*
FORM GET_DATA_Z1013492_MAINT.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM Z1013492_TPAYMEN WHERE
(VIM_WHERETAB) .
    CLEAR Z1013492_MAINT .
Z1013492_MAINT-MANDT =
Z1013492_TPAYMEN-MANDT .
Z1013492_MAINT-PAYMENT_ID =
Z1013492_TPAYMEN-PAYMENT_ID .
Z1013492_MAINT-BILL_NO =
Z1013492_TPAYMEN-BILL_NO .
    SELECT * FROM Z1013492_TBILL WHERE
BILL_NO = Z1013492_TPAYMEN-BILL_NO .
      EXIT.
    ENDSELECT.
    SELECT * FROM Z1013492_TOFFER WHERE
OFFER_ID = Z1013492_TPAYMEN-OFFER_ID .
Z1013492_MAINT-OFFER_ID =
Z1013492_TOFFER-OFFER_ID .
      EXIT.
    ENDSELECT.
    SELECT * FROM Z1013492_TUSER WHERE
USER_ID = Z1013492_TPAYMEN-USER_ID .
      EXIT.
    ENDSELECT.
<VIM_TOTAL_STRUC> = Z1013492_MAINT.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_Z1013492_MAINT .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO Z1013492_MAINT.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_Z1013492_MAINT-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM Z1013492_TPAYMEN WHERE
  PAYMENT_ID = Z1013492_MAINT-PAYMENT_ID AND
  BILL_NO = Z1013492_MAINT-BILL_NO .
    IF SY-SUBRC = 0.
    DELETE Z1013492_TPAYMEN .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM Z1013492_TPAYMEN WHERE
  PAYMENT_ID = Z1013492_MAINT-PAYMENT_ID AND
  BILL_NO = Z1013492_MAINT-BILL_NO .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR Z1013492_TPAYMEN.
    ENDIF.
Z1013492_TPAYMEN-MANDT =
Z1013492_MAINT-MANDT .
Z1013492_TPAYMEN-PAYMENT_ID =
Z1013492_MAINT-PAYMENT_ID .
Z1013492_TPAYMEN-BILL_NO =
Z1013492_MAINT-BILL_NO .
    IF SY-SUBRC = 0.
    UPDATE Z1013492_TPAYMEN ##WARN_OK.
    ELSE.
    INSERT Z1013492_TPAYMEN .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_Z1013492_MAINT-UPD_FLAG,
STATUS_Z1013492_MAINT-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_Z1013492_MAINT.
  SELECT SINGLE * FROM Z1013492_TPAYMEN WHERE
PAYMENT_ID = Z1013492_MAINT-PAYMENT_ID AND
BILL_NO = Z1013492_MAINT-BILL_NO .
Z1013492_MAINT-MANDT =
Z1013492_TPAYMEN-MANDT .
Z1013492_MAINT-PAYMENT_ID =
Z1013492_TPAYMEN-PAYMENT_ID .
Z1013492_MAINT-BILL_NO =
Z1013492_TPAYMEN-BILL_NO .
    SELECT * FROM Z1013492_TBILL WHERE
BILL_NO = Z1013492_TPAYMEN-BILL_NO .
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
    ENDIF.
    SELECT * FROM Z1013492_TOFFER WHERE
OFFER_ID = Z1013492_TPAYMEN-OFFER_ID .
Z1013492_MAINT-OFFER_ID =
Z1013492_TOFFER-OFFER_ID .
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
      CLEAR Z1013492_MAINT-OFFER_ID .
    ENDIF.
    SELECT * FROM Z1013492_TUSER WHERE
USER_ID = Z1013492_TPAYMEN-USER_ID .
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_Z1013492_MAINT USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE Z1013492_MAINT-PAYMENT_ID TO
Z1013492_TPAYMEN-PAYMENT_ID .
MOVE Z1013492_MAINT-BILL_NO TO
Z1013492_TPAYMEN-BILL_NO .
MOVE Z1013492_MAINT-MANDT TO
Z1013492_TPAYMEN-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'Z1013492_TPAYMEN'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN Z1013492_TPAYMEN TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'Z1013492_TPAYMEN'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_Z1013492_MAINT USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
Z1013492_TPAYMEN-MANDT =
Z1013492_MAINT-MANDT .
Z1013492_TPAYMEN-PAYMENT_ID =
Z1013492_MAINT-PAYMENT_ID .
Z1013492_TPAYMEN-BILL_NO =
Z1013492_MAINT-BILL_NO .
    SELECT * FROM Z1013492_TBILL WHERE
BILL_NO = Z1013492_TPAYMEN-BILL_NO .
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
    ENDIF.
    SELECT * FROM Z1013492_TOFFER WHERE
OFFER_ID = Z1013492_TPAYMEN-OFFER_ID .
Z1013492_MAINT-OFFER_ID =
Z1013492_TOFFER-OFFER_ID .
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
      CLEAR Z1013492_MAINT-OFFER_ID .
    ENDIF.
    SELECT * FROM Z1013492_TUSER WHERE
USER_ID = Z1013492_TPAYMEN-USER_ID .
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
    ENDIF.
ENDFORM.
