TYPE-POOL ZTEJ .

TYPES: BEGIN OF ZTEJ_STR,
       ZTEJ_BANK TYPE Z1013492_DA_TYP-BANK_ACCOUNT,
       ZTEJ_INT  TYPE Z1013492_DA_TYP-NAME,
       ZTEJ_QUANT TYPE Z1013492_DA_TYP-QUANT,
       END OF ZTEJ_STR.
